// <auto-generated />
using System;
using DatabaseLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseLayer.Migrations
{
    [DbContext(typeof(OrhedgeContext))]
    [Migration("20200710132408_AddMaxLengthConstraints")]
    partial class AddMaxLengthConstraints
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DatabaseLayer.Entity.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("CategoryId");

                    b.HasIndex("CourseId", "Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DatabaseLayer.Entity.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired();

                    b.Property<DateTime>("SentOn");

                    b.Property<int>("StudentId");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("StudentId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("DatabaseLayer.Entity.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("CourseId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DatabaseLayer.Entity.CourseStudyProgram", b =>
                {
                    b.Property<int>("StudyProgram");

                    b.Property<int>("CourseId");

                    b.Property<int>("Semester");

                    b.Property<int>("StudyYear");

                    b.HasKey("StudyProgram", "CourseId", "Semester");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseStudyPrograms");
                });

            modelBuilder.Entity("DatabaseLayer.Entity.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("Index");

                    b.Property<string>("LastName");

                    b.Property<int>("Privilege");

                    b.Property<string>("RegistrationCode");

                    b.Property<DateTime>("Timestamp");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.HasKey("RegistrationId");

                    b.HasIndex("Email");

                    b.HasIndex("RegistrationCode")
                        .IsUnique()
                        .HasFilter("[RegistrationCode] IS NOT NULL");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("DatabaseLayer.Entity.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63);

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.Property<string>("Photo");

                    b.Property<int>("PhotoVersion");

                    b.Property<int>("Privilege");

                    b.Property<double>("Rating");

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Index")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DatabaseLayer.Entity.StudyMaterial", b =>
                {
                    b.Property<int>("StudyMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("StudentId");

                    b.Property<double>("TotalRating");

                    b.Property<DateTime>("UploadDate");

                    b.Property<string>("Uri")
                        .IsRequired();

                    b.HasKey("StudyMaterialId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StudentId");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("StudyMaterials");
                });

            modelBuilder.Entity("DatabaseLayer.Entity.StudyMaterialRating", b =>
                {
                    b.Property<int>("StudentId");

                    b.Property<int>("StudyMaterialId");

                    b.Property<double>("Rating");

                    b.HasKey("StudentId", "StudyMaterialId");

                    b.HasIndex("StudyMaterialId");

                    b.ToTable("StudyMaterialRatings");
                });

            modelBuilder.Entity("DatabaseLayer.Entity.Category", b =>
                {
                    b.HasOne("DatabaseLayer.Entity.Course", "Course")
                        .WithMany("Categories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DatabaseLayer.Entity.ChatMessage", b =>
                {
                    b.HasOne("DatabaseLayer.Entity.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DatabaseLayer.Entity.CourseStudyProgram", b =>
                {
                    b.HasOne("DatabaseLayer.Entity.Course", "Course")
                        .WithMany("CourseStudyPrograms")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DatabaseLayer.Entity.StudyMaterial", b =>
                {
                    b.HasOne("DatabaseLayer.Entity.Category", "Category")
                        .WithMany("StudyMaterials")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DatabaseLayer.Entity.Student", "Student")
                        .WithMany("StudyMaterials")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DatabaseLayer.Entity.StudyMaterialRating", b =>
                {
                    b.HasOne("DatabaseLayer.Entity.Student", "Student")
                        .WithMany("StudyMaterialRatingsStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DatabaseLayer.Entity.StudyMaterial", "StudyMaterial")
                        .WithMany("StudyMaterialRatings")
                        .HasForeignKey("StudyMaterialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
